export const zoomerism = [
	"girl dinner fr fr",
	"mother has mothered",
	"its giving main character energy",
	"slay queen purr",
	"spill the tea bestie",
	"no because literally same",
	"not me being obsessed",
	"atp i cant",
	"the grip he has on me",
	"material gworl",
	"periodt pooh",
	"sis went off",
	"girlie pop snapped",
	"ate and left no crumbs",
	"understood the assignment",
	"this is your sign to...",
	"i'm literally screaming crying throwing up",
	"that's so mother of you",
	"im so slay for this",
	"queen behavior only",
	"the girls that get it get it",
	"she's giving everything",
	"its giving pick me",
	"not the ick",
	"gaslight gatekeep girlboss",
	"pop off queen",
	"cries in poor",
	"real hot girl behavior",
	"slayed and stayed",
	"icon behavior only",
	"its giving energy vampire",
	"me when i lie",
	"crying rn",
	"actually unhinged and real",
	"my toxic trait is",
	"borderline unhinged rn",
	"skull emoji fr",
	"based and real",
	"zero rizz behavior",
	"my brother in christ",
	"i'm so cooked",
	"absolutely zonked",
	"down astronomical",
	"throwing up and crying rn",
	"slay bestie fr",
	"that's so valid",
	"literally me fr fr",
	"no thoughts head empty",
	"touch grass challenge",
	"its giving mental breakdown",
	"we stay losing",
	"caught lacking in the library",
	"professor got me bricked up fr",
	"rizzing up the TA",
	"living my worst life rn",
	"chronically online behavior",
	"gonna kms",
	"zero cap no printer",
	"not me acting unhinged",
	"bestie i'm fighting for my life",
	"down horrendous in the trenches",
	"actually deranged behavior",
	"this ain't bussin",
	"straight bussin no cap fr fr",
	"deceased and real",
	"actual content brain damage",
	"banger stream fr fr",
	"absolutely goated",
	"skill issue",
	"no shot",
	"on god fr fr",
	"ain't no way bruh",
	"copium",
	"hopium",
	"malding",
	"poggers",
	"actual NPC behavior",
	"real and true",
	"main character moment",
	"rizz god",
	"chat's wildin",
	"literally farming",
	"stream's bussin",
	"kinda mid ngl",
	"caught in 4k",
	"deadass",
	"respectfully though",
	"ratio + L + fell off",
	"he's him",
	"lowkey fire",
	"real talk no cap",
	"literally me fr",
	"actual demon behavior",
	"parasocial andy",
	"no cap fr fr",
	"sheesh",
	"bussin",
	"based",
	"monkaW",
	"sadge",
	"lowkey",
	"highkey",
	"W rizz",
	"L take",
	"ratio'd",
	"living rent free",
	"touch grass",
	"sus",
	"bricked up",
	"down bad",
	"finna",
	"respectfully",
	"valid",
	"slaps",
	"hits different",
	"not the vibe",
	"that's wild",
	"iykyk",
	"unhinged",
	"bestie",
	"slay",
	"period",
	"bet",
	"living my best life",
	"rent is due",
	"real life npc moment",
	"i fear",
	"crying and throwing up",
	"this tweet will bang",
	"common W",
	"common L",
	"fear",
	"shaking and crying rn",
	"goes hard fr",
	"so true bestie",
	"real",
	"not real",
	"tweaking fr",
	"sleeping on this fr",
	"sleeping on me fr",
	"big yikes",
	"touch grass challenge",
	"actually crying rn",
	"naur",
	"npc energy",
	"ong fr",
	"ate that",
	"devious lick",
	"no printer just fax",
	"it's giving",
	"boy math",
	"girl math",
	"mob wife aesthetic",
	"core memory",
	"that's camp",
	"the masculine urge to",
	"the feminine urge to",
	"drip check",
	"absolutely cooked",
	"zero bitches",
	"real derogatory",
	"crying screaming throwing up",
	"this goes so hard",
	"smoking that pack",
	"might delete later",
	"vibing and thriving",
	"main pop girl",
	"not me when i",
	"caught in 8k ultra hd",
	"living laughing loving",
	"dinner reveal",
	"real behavior",
	"im actually crying",
	"we fear",
	"you ate that",
	"purr",
	"mother",
	"father",
	"sistered",
	"brothered",
	"peak fiction",
	"crying shaking throwing up",
	"i was today years old",
	"core",
	"sleep with one eye open",
	"i just know",
	"omg slay",
	"who gonna tell them",
	"no thoughts just vibes",
	"real cinema",
	"raw as hell",
];
